function [ output_args ] = CreateRobot(r,Motors)
% tabelka DH robota powinna byc wpsiana
%ale ze to konkretny robot to wymiary po kolei
% od pierwszego silnika
% r0 r1 r2 r3
% !!! r0= to wysokosc drugiego silnika od pierwszego
% nasze r:
% r=[48,64,130,180];

% Motors motory
Rmax=r(2)+r(3)+r(4);

output_args=struct('r',r,...
    'Motors',Motors,...
    'curTh',[0 0 0],...
    'Rmax',Rmax,... %max zasieg robota
    'Motor1',Motors(1),...
    'Motor2',Motors(2),...
    'Motor3',Motors(3),...
    'curTh1',0,...
    'curTh2',0,...
    'curTh3',0);
fprintf('Robot stworzony\n')
end

